### ISSUE TITLE
Accelorometer waking PineTime

### ISSUE THREAD

**Issue by fukuimaunicorn** [wasp-os/wasp-os#191]
I'd love to see a feature where the watch turns on when you flip it towards yourself. I would do it myself but I'm only now starting to learn micropython. So if nobody will do it in the next 3month, see you then. ^^

**Comment by fukuimaunicorn** [comment]
Oh, i just found this thread: https://github.com/daniel-thompson/wasp-os/pull/149

Waking the watch by shaking. But I'd rather have it only wake when flipping your arm towards youself, as it may shake on many other ocasions. Also i have no idea if this is the right place for somehting like this, if not I am really sorry, just delete it then.

**Comment by fgaz** [comment]
Duplicate of #131
