### ISSUE TITLE
Any attempts on nRF52832 fitness tracker wrist bands?

### ISSUE THREAD

**Issue by abishekmuthian** [wasp-os/wasp-os#261]
nRF52832 watches are getting harder to find where I live, PineTime & Aliexpress shipments are not allowed as well but there are these [fitness tracker wristbands](https://www.flipkart.com/trending-fitness-fp09-tracker-free-diet-plan/p/itm307506442f9bd) available relatively cheap under various brand names.

Has anyone attempted to flash wasp-os on any of those? I understand that the UI would need work to function on the 160*80 display but it would be promising if anyone managed to flash successfully to the device without dismantling it.

**Comment by daniel-thompson** [comment]
> Has anyone attempted to flash wasp-os on any of those? I understand that the UI would need work to function on the 160*80 display but it would be promising if anyone managed to flash successfully to the device without dismantling it.

It's not really the attempt to flash wasp-os that is important. What is important is attempting to flash anything! Until you know how to take ownership of your device and run your own code on it then wasp-os isn't the best place to start.

Once you do have ownership there are tricks, like disabling all the drivers so you can experiment with the device via the REPL-over-BLE connection, that make wasp-os a pretty nice development platform. However you need ownership of your device first.
