### ISSUE TITLE
Application Not Start P8 (Solved)

### ISSUE THREAD

**Issue by faustolnx** [wasp-os/wasp-os#267]
Hello, I have compiled whit command 
make -j `nproc` BOARD=p8 all
But I get this error
Failed to import ecdsa, cannot do signing
Zip created at build-p8/micropython.zip
I upload the zip file whit nrf connect, but the application not start.
What i have to do to correct these error?
Thanks in avance.

**Comment by SteveAmor** [comment]
Hi @faustolnx if I remember correctly, the ecdsa error doesn't matter but you can install the Python ecdsa package to resolve it `pip3 install ecdsa`
However, some more information is required to fix the application not starting.  Does it stop with any text on the screen? Is I an original Colmi P8?
