### ISSUE TITLE
Touch events not registering on buttons

### ISSUE THREAD

**Issue by charliehawco** [wasp-os/wasp-os#287]
Hi all -

I'm having some trouble with the various buttons - it seems that any touch event in the button class does not get activated if touched, only the 'base' application gets pressed - is there any way to fix this?

**Comment by daniel-thompson** [comment]
Touch events are never delivered directly to widgets. They are delivered to applications and the app must check if the touch event hits the button. See https://github.com/daniel-thompson/wasp-os/blob/b8a50db03c1f7655b846c59d6903e27d54bd82ae/wasp/apps/disaBLE.py#L55 for an example.

**Comment by jonnor** [comment]
This issue seem to have a resolution, and can probably be closed.
