### ISSUE TITLE
 wasp-os-dev does not exist in docker hub image repo?

### ISSUE THREAD

**Issue by ghost** [wasp-os/wasp-os#342]
every time i try to build using the docker i get the error
`Error response from daemon: pull access denied for wasp-os-dev, repository does not exist o
r may require 'docker login': denied: requested access to the resource is denied`
Im logged into my account too

**Comment by beardeddude** [comment]
Its been a while but putting this here for others. Don't run the docker shell script as root

**Comment by tolidano** [comment]
Or just do this if you're on a Mac and in the staff group:

```
 RUN set -xe; \
     adduser --gecos "" --disabled-password --uid $uid --gid $gid user;
 # addgroup --gid $gid user; \
```
