### ISSUE TITLE
Resistor colour code face for wasp?

### ISSUE THREAD

**Issue by drtonyr** [wasp-os/wasp-os#354]
Hackaday features all sorts of interesting things (that's how I got here) including a clock that shows the time using the resistor colour code ([hackaday](https://hackaday.com/2021/07/15/a-perfect-clock-for-any-hackers-ohm/)).

This is trivial to write for WASP, so I've done it.  I'm very pleased with the result ([video](https://photos.app.goo.gl/hvZGsxNAidH8nMgD8)).  Does the project want it?

EDIT:  After feedback from my son I've made the date use the same resistor colour code - he was right, it does look a lot better.  I've also added a bit of space to separate out the fields in HHMMS and DDMMYYYY.  Video link above changed.

EDIT:  This is down to only 767 bytes of mpy now, so it's not a huge overheard.  What's more, a lot is duplicated code with the other watch faces, we could easily make a Face class and save considerable space overall.

**Comment by kj7rrv** [comment]
Would you mind sharing the code for this?

**Comment by drtonyr** [comment]
Not at all.  However, it's a while since I did any WASP work and things have changed.  Attached is the code.  I know that WASP is more configurable now, so it's easier to add code that doesn't get loaded by default.  Once I get up to speed again I have a few things to merge in.
[resistor_clock.py.txt](https://github.com/wasp-os/wasp-os/files/11871700/resistor_clock.py.txt)

**Comment by drtonyr** [comment]
Closing this issue as now merged in #447
