### ISSUE TITLE
Any way to reduce brightness to less than 1 ?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [wasp-os/wasp-os#373]
Hi,

I stumbled upon #68 but it's pretty old and I figured it could be worth creating a new issue.

I'm basically looking for a way to reduce brightness less than the current threshold. This would be handy for [my SleepTracking app](https://github.com/thiswillbeyourgithub/sleep_tracker_pinetime_wasp-os) :)

Any idea if it's possible?

Thanks!

**Comment by fgaz** [comment]
As far as I understand, pwm on the first backlight pin would make it possible. You could get it very low.
