### ISSUE TITLE
Charging level does not update without rebooting

### ISSUE THREAD

**Issue by AeneasChristodoulou** [wasp-os/wasp-os#385]
Hey guys, I'm pretty new to WaspOS. 
My PineTime does not update its charging level in WaspOS without me manually rebooting it.
I'm using the latest "official" version following the installation guide. I'd assume this is just me being stupid here?

**Comment by beardeddude** [comment]
also the official build is very old. If you build yourself you will see lots of improvments

**Comment by fgaz** [comment]
I'm pretty sure it's because of this: https://github.com/wasp-os/wasp-os/pull/318#pullrequestreview-1074764497

Looks like it wasn't reverted yet
