### ISSUE TITLE
"make check" returns pytest Error 127

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [wasp-os/wasp-os#417]
Hi!

I'm not familiar with pytest and can't seem to make `make check` command in the master branch.

I get instantly : 
```
PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=.:wasp/boards/simulator:wasp:wasp/apps/system \
pytest-3 -v -W ignore  wasp/boards/simulator
/bin/sh: 1: pytest-3: not found
make: *** [Makefile:126: check] Error 127
```

Can anyone give me pointers on this?

**Comment by fgaz** [comment]
> pytest-3: not found

If your `pytest` isn't called `pytest-3` (mine also isn't) you can override it with `PYTEST=name_of_pytest`. For example mine is called just `pytest` so I do `make check PYTEST=pytest`.

**Comment by fgaz** [comment]
#419 could help avoid this kind of issue
