### ISSUE TITLE
I think I accidentally bricked my pinetime

### ISSUE THREAD

**Issue by Onni3000** [wasp-os/wasp-os#438]
Today I tried installing wasp os to my pinetime. I was able to install the bootloader without problems, but now when I try to install the wasp os to it, its just stuck at 0%

(For some reason it didn't allow me to put the pictures here so Ill just put them into the comments.)

**Comment by Onni3000** [comment]
![Screenshot_2023-07-15-12-25-52-397_no.nordicsemi.android.mcp.jpg](https://github.com/wasp-os/wasp-os/assets/69005390/36cbd4a9-2eb5-40da-8127-f73194c3b92a)

![IMG_20230715_122602.jpg](https://github.com/wasp-os/wasp-os/assets/69005390/ef8febd9-ce57-489b-8f0a-adc9e0e1ec67)

**Comment by SteveAmor** [comment]
Did you use nRF Connect to install the bootloader? Recent versions of nRF Connect have stopped working for installing firmware.  Can you use another program like Gadgetbridge?

**Comment by Onni3000** [comment]
> Did you use nRF Connect to install the bootloader? Recent versions of nRF Connect have stopped working for installing firmware. Can you use another program like Gadgetbridge?

Thank you for response!

I first tried to install with nRF Connect, but it didn't work so I decided to try to do it with Gadgetbridge (which worked), but Gadgetbridge apparently doesn't support this device now that it has this bootloader so I am unable to use it to install the micropython.zip.

**Comment by Onni3000** [comment]
I was able to get Wasp OS installed after downloading an older version of nRF Connect.

**Comment by Brulijam** [comment]
Hi I have the same problem. Which version of nrf connect worked for you?

**Comment by GaryM0101** [comment]
You can try 4.24.3, versions after that are no longer supported.

On 2024-02-26 15:49, Julian Brammer wrote:

> Hi I have the same problem. Which version of nrf connect worked for you? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/wasp-os/wasp-os/issues/438#issuecomment-1965532558
[2]
