### ISSUE TITLE
nRF Connect 4.26.0 (latest version) fails to install the Wasp boot loader - Pinetime

### ISSUE THREAD

**Issue by GaryM0101** [wasp-os/wasp-os#472]
The latest version of nRF Connect 4.26.0 fails to install the Wasp boot loader on the Pinetime.  The workaround is to have the user install an older version, in this case 4.24.3.  The Infinitime project now uses Gagetbridge for their installs; they found every new nRF version was failing to do updates for them. 

We should document that folks use the older version of nRF Connect 4.24.3 for installing Wasp as the workaround for Andriod.
https://github.com/NordicSemiconductor/Android-nRF-Connect/releases

Are there any other DFU phone apps like nRF Connect that we can use for the Pinetime, Gadgetbridge maybe?

**Comment by GaryM0101** [comment]
Well...it has been confirmed by a user that gadgetbridge can indeed install Wasp and then go back to Infinitime. We'll have to update the docs for this as well.

**Comment by fgaz** [comment]
Yes I remember using gadgetbridge too and it worked well

**Comment by GaryM0101** [comment]
We might add this troubleshooting step as well. 

_Caleb Fontenot (He/Him) -- Today at 4:42 AM_
_Yes, but as a troubleshooting step, I had uninstalled GadgetBridge when
I was trying to flash the watch and GadgetBridge only lets you flash
devices you've already paired with it first. Because the PineTime was
stuck in DFU mode, it wouldn't pair with my phone, so I couldn't use
GadgetBridge..._

On 2023-10-18 07:09, Francesco Gazzetta wrote:

> Yes I remember using gadgetbridge too and it worked well 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/wasp-os/wasp-os/issues/472#issuecomment-1768545991
[2]

**Comment by GaryM0101** [comment]
Close with implementation of PR #480
