### ISSUE TITLE
docs: installation: Installing wasp-bootloader -- nRF Connect for Android

### ISSUE THREAD

**Issue by GaryM0101** [wasp-os/wasp-os#475]
We should no longer recommend nRFConnect for installing the Wasp bootloader for Pine64 PineTime devices running Infinitime. nRFConnect is closed sourced, and versions after 4.24.3 no longer work with PineTime.

We should recommend using GadgetBridge instead. Some notes we should address:
After successfully flashing the bootloader, GadgetBridge re-scans and lists PINE DFU as an unsupported device. This prevents users from uploading/DFU the micropython.py file.

Workaround:
1. In GadgetBridge, go to discovery and pairing options and allow unsupported devices.
2. The Pinetime will show up as an unsupported device. Long-press it and select Add as a test device. A list of devices will show up. Scroll down to Pinetime and select it.
3. The device will be added now. Upload the micropython file now.

**Comment by tolidano** [comment]
I have a Colmi P8. I am at the point where I am trying to send micro python but it fails to start the transfer. I have tried the built from source version and the release 0.4.1 version. The bluetooth icon goes blue on the watch but no transfer ever occurs. 

I am now attempting to use GadgetBridge, which I downloaded from F-Droid. I am able to add the P8DFU device but there is no option to long press to add as a test device.
