### ISSUE TITLE
how do install wasp os  from infinity time with gadgetbridge

### ISSUE THREAD

**Issue by RMHogervorst** [wasp-os/wasp-os#490]
Hi there I found instructions to go from Infiniti time to waspos but it requiteres a bootloader?and that is not provided by the release process.
Could you provide some guidance for that? I don't really want to compile this project myself yet.

**Comment by fgaz** [comment]
You can find it in the [releases](https://github.com/wasp-os/wasp-os/releases) as documented [here](https://wasp-os.readthedocs.io/en/latest/install.html#binary-downloads)

**Comment by RMHogervorst** [comment]
I don't know if it wasn't there before, and now is, but the compressed file in de release does now contain all the components needed for flashing wasp-os. Thanks!
