### ISSUE TITLE
Installation videos with Gadgetbridge

### ISSUE THREAD

**Issue by fgaz** [wasp-os/wasp-os#503]
The installation videos at https://wasp-os.readthedocs.io/en/latest/install.html use nrfconnect and are outdated.

**Comment by GaryM0101** [comment]
Correct I've been meaning to do a PR from issue #476

Note to Gary, start cracking!

**Comment by fgaz** [comment]
And note for myself, check open issues before opening a new one :sweat_smile: 

Closing as duplicate of #476
