### ISSUE TITLE
What is the status on installing waspos on a PineTime?

### ISSUE THREAD

**Issue by arghunter** [wasp-os/wasp-os#504]
Are the docs up to date and what is the latest stable build? I saw plans for a Gadgetbridge install of waspos. Was that ever made?

**Comment by GaryM0101** [comment]
Docs are up to date with although a video has to be made, not a show stopper by any means. We are on continuous integration (CI) builds: https://github.com/wasp-os/wasp-os/actions?query=is%3Asuccess+branch%3Amaster+workflow%3Abinary

Gadgetbridge install can be found here: https://wasp-os.readthedocs.io/en/latest/install.html#id28

Cheers!

**Comment by arghunter** [comment]
Great thanks so much!
