### ISSUE TITLE
GadgetBridge says PineDFU is unsupported and DaFlsher connects but doesn't transfer OS install data

### ISSUE THREAD

**Issue by arghunter** [wasp-os/wasp-os#505]
Exactly as the title states. The install isn't working

**Comment by GaryM0101** [comment]
See the docs to get the workaround... 

https://wasp-os.readthedocs.io/en/latest/install.html#main-os-gadgetbridge

Cheers! 

On 2024-09-23 18:59, Armaan Gomes wrote:

> Exactly as the title states. The install isn't working 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
 

Links:
------
[1] https://github.com/wasp-os/wasp-os/issues/505
[2]

**Comment by arghunter** [comment]
Thank you so much,  and how can i swap between wasp and infinitime?

**Comment by GaryM0101** [comment]
See the docs for restoring the Pintime factory firmware... 

https://wasp-os.readthedocs.io/en/latest/install.html#gadgetbridge-for-android


And please close this issue. 

Cheers!

On 2024-09-23 19:31, Armaan Gomes wrote:

> Thank you so much, and how can i swap between wasp and infinitime? 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you commented.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/wasp-os/wasp-os/issues/505#issuecomment-2369987512
[2]

**Comment by arghunter** [comment]
Thank you
